# Generated by Django 6.0.3 on 2026-03-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Material')),
                ('unidad_medida', models.CharField(help_text='Ej: cm2, metros, unidades', max_length=50)),
                ('cantidad_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en Stock')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('talla', models.CharField(max_length=10, verbose_name='Talla')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mano de Obra')),
                ('proceso_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.procesobase')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='inventario.referencia')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Consumida')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.referencia')),
            ],
        ),
    ]
