# Generated by Django 6.0.3 on 2026-03-04 20:44

import django.db.models.deletion
from django.db import migrations, models


def crear_tipos_iniciales(apps, schema_editor):
    TipoMaterial = apps.get_model('inventario', 'TipoMaterial')
    tipos = ['Capellada', 'Forro', 'Suela', 'Herraje', 'Recuño', 'Tacón']
    for nombre in tipos:
        TipoMaterial.objects.get_or_create(nombre=nombre)


def asignar_tipo_default(apps, schema_editor):
    """Asigna el primer TipoMaterial a materiales existentes."""
    TipoMaterial = apps.get_model('inventario', 'TipoMaterial')
    Material = apps.get_model('inventario', 'Material')
    tipo_default = TipoMaterial.objects.first()
    if tipo_default:
        Material.objects.filter(tipo__isnull=True).update(tipo=tipo_default)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        # 1. Crear tabla TipoMaterial
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Material')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
            },
        ),
        # 2. Insertar los 6 tipos iniciales
        migrations.RunPython(crear_tipos_iniciales, migrations.RunPython.noop),
        # 3. Quitar unique de nombre (ahora es unique_together con tipo)
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Material'),
        ),
        # 4. Agregar FK nullable temporalmente
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.tipomaterial', verbose_name='Tipo'),
            preserve_default=False,
        ),
        # 5. Asignar tipo default a materiales existentes
        migrations.RunPython(asignar_tipo_default, migrations.RunPython.noop),
        # 6. Hacer la FK NOT NULL
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.tipomaterial', verbose_name='Tipo'),
        ),
        # 7. unique_together
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('tipo', 'nombre')},
        ),
    ]
