# Generated by Django 6.0.2 on 2026-08-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_tipozapato_referencia_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumomaterial',
            options={'verbose_name': 'Consumo de material', 'verbose_name_plural': 'Consumos de material'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='procesobase',
            options={'verbose_name': 'Proceso', 'verbose_name_plural': 'Procesos'},
        ),
        migrations.AlterModelOptions(
            name='procesoreferencia',
            options={'verbose_name': 'Proceso de referencia', 'verbose_name_plural': 'Procesos de referencia'},
        ),
        migrations.AlterModelOptions(
            name='referencia',
            options={'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
    ]
