# Generated by Django 6.0.3 on 2026-03-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre o Empresa')),
                ('contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_fabricada', models.PositiveIntegerField(default=0, verbose_name='Cantidad Fabricada')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.referencia')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_realizada', models.PositiveIntegerField(verbose_name='Cantidad Realizada')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_trabajo', to='produccion.detalleorden')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='empleados.empleado')),
                ('proceso_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.procesoreferencia')),
            ],
        ),
    ]
