# Generated by Django 6.0.2 on 2026-08-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_orden_materiales_descontados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'verbose_name': 'Orden de producción', 'verbose_name_plural': 'Órdenes de producción'},
        ),
        migrations.AlterModelOptions(
            name='registrotrabajo',
            options={'verbose_name': 'Registro de trabajo', 'verbose_name_plural': 'Registros de trabajo'},
        ),
    ]
